
# This file is automatically generated

__version__ = '0.9.6'
__comments__ = """merged release test fixes"""
__date__ = '2014-02-24 16:31:56 -0500'
__commit__ = '6b1ff84b5c480c5e232f51908156925f4c7eec1e'
