
# This file is automatically generated

__version__ = '0.6.3'
__comments__ = """added some time.sleep to allow for certain GUI actions to complete. test...
Merge pull request #1384 from hschilling/P44474497-multiple-file-remove"""
__date__ = '2013-06-07 11:28:36 -0700'
__commit__ = '0fc220cf11fe0f2c55678c86f9d4c5e5f858be46'
