
# This file is automatically generated

__version__ = '0.9.2'
__comments__ = """bye bye gists
Merge pull request #1525 from kmarsteller/dev"""
__date__ = '2013-12-11 07:52:07 -0800'
__commit__ = '0fc47a392763eb37c9ef5a96ab0d6f3c044ef050'
