
# This file is automatically generated

__version__ = '0.0.11'
__revision__ = """revno: 421
committer: Bret Naylor <Bret.A.Naylor@nasa.gov>
branch nick: windows_fixes
timestamp: Thu 2010-04-22 18:31:38 -0400
message:
  added openmdao.devtools package, more changes to windows installation scripts
"""
__date__ = '2010-04-22'
