
# This file is automatically generated

__version__ = '0.2.5'
__comments__ = """One last fix for plugins
Merge pull request #894 from Kenneth-T-Moore/master"""
__date__ = '2012-03-14 14:03:21 -0700'
__commit__ = '87f12c88906f7968f669ff07dafa773215906602'
