
# This file is automatically generated
# Do not place this file in version control

__version__ = '0.0.2'
__revision__ = """revno: 356 [merge]
committer: Bret Naylor <bnaylor@grc.nasa.gov>
branch nick: packaging
timestamp: Wed 2010-03-31 10:20:20 -0400
message:
  merged from lp
"""
__date__ = '2010-04-02'
