
# This file is automatically generated

__version__ = '0.4.2'
__comments__ = """added binary building of openmdao examples on osx to 'release build'
Merge pull request #1260 from naylor-b/mac_binaries"""
__date__ = '2013-01-17 12:51:53 -0800'
__commit__ = '1679fcba1f7013cdce7db46429a4506783cab051'
