
# This file is automatically generated

__version__ = '0.0.10'
__revision__ = """revno: 409
committer: Bret Naylor <Bret.A.Naylor@nasa.gov>
branch nick: windows_fixes
timestamp: Thu 2010-04-22 10:23:19 -0400
message:
  windows install fixes
"""
__date__ = '2010-04-22'
