
# This file is automatically generated

__version__ = '0.0.9'
__revision__ = """revno: 351
committer: Bret Naylor <bret@ubuntu>
branch nick: openmdao
timestamp: Thu 2010-04-15 15:59:01 -0400
message:
  added tearDown function to units test because it was corrupting the default unit set and causing the enginedesign test to fail
"""
__date__ = '2010-04-15'
