
# This file is automatically generated

__version__ = '0.3.0'
__comments__ = """Fix26
Merge pull request #1136 from kmarsteller/fix26"""
__date__ = '2012-09-13 12:50:21 -0700'
__commit__ = '3aac6053c070f14df89d23f98f0bff3cf17c0e2c'
