
# This file is automatically generated

__version__ = '0.0.12'
__revision__ = """revno: 429 [merge]
committer: Bret Naylor <bnaylor@grc.nasa.gov>
branch nick: windows_fixes
timestamp: Fri 2010-04-23 08:46:34 -0400
message:
  merged from trunk
"""
__date__ = '2010-04-23'
