
# This file is automatically generated

__version__ = '0.0.2'
__revision__ = """revno: 325
committer: Bret Naylor <bnaylor@grc.nasa.gov>
branch nick: openmdao
timestamp: Tue 2010-04-13 15:32:38 -0400
message:
  interim commit
"""
__date__ = '2010-04-13'
