
# This file is automatically generated

__version__ = '0.0.18'
__revision__ = """revno: 405 [merge]
committer: Kenneth Moore <Kenneth.T.Moore-1@nasa.gov>
branch nick: main
timestamp: Wed 2010-06-09 12:18:26 -0400
message:
  T26 started (Fortran namelist writing); more work on T303 (output file parsing for file wrapping)
"""
__date__ = '2010-06-09'
