
# This file is automatically generated

__version__ = '0.0.8'
__revision__ = """revno: 349
committer: Bret Naylor <bret@ubuntu>
branch nick: openmdao
timestamp: Thu 2010-04-15 15:31:43 -0400
message:
  fixed version mixup in mkinstaller.py (again)
"""
__date__ = '2010-04-15'
