
# This file is automatically generated

__version__ = '0.2.2'
__comments__ = """removed PyYAML and fixed a bug in the remote test scripts
Merge pull request #735 from naylor-b/misc_testing"""
__date__ = '2011-12-09 05:51:29 -0800'
__commit__ = 'fb25eb6292cfd23e9243a62a3d0f2acfaba4108b'
