
# This file is automatically generated

__version__ = '0.10.3'
__comments__ = """Removed automatic OptProblem and architecture detection.
Merge pull request #1841 from crobinsonut/fix-test-mdao-test-suite"""
__date__ = '2014-11-12 15:29:45 -0500'
__commit__ = '0c150990b48d7f41a669294cb28b296c172ea4d4'
