
# This file is automatically generated

__version__ = '0.6.4'
__comments__ = """API INCOMPATIBILITY: drop init args on Container, Component, Driver, and Assembly
Merge pull request #1385 from setowns1/bug"""
__date__ = '2013-06-07 13:55:55 -0700'
__commit__ = 'f72209be8e7104b74c86b3e86a02c69365b9be9d'
