
# This file is automatically generated

__version__ = '0.1.6'
__revision__ = """revno: 559 [merge]
tags: T468
committer: Tina G Grzincic <tina.g.grzincic@nasa.gov>
branch nick: TG-T468-fileparser
timestamp: Wed 2011-05-04 10:30:45 -0400
message:
  T468 - Created the ability for the FileParser to handle comments
"""
__date__ = '2011-05-05'
