
# This file is automatically generated

__version__ = '0.6.2'
__comments__ = """Merge branch 'dev' of github.com:OpenMDAO/OpenMDAO-Framework into dev"""
__date__ = '2013-05-10 15:32:29 -0400'
__commit__ = '7d5bed2179c60d34d3ee34f16c12f54a962baa6c'
