
# This file is automatically generated

__version__ = '0.5.0'
__comments__ = """another quick fix for test failure
Merge pull request #1267 from swryan/gui"""
__date__ = '2013-01-24 18:03:43 -0800'
__commit__ = '01324da5261772c450c558ad982e66e300d34ce0'
