
# This file is automatically generated

__version__ = '0.0.0'
__comments__ = """Made regex for release docs check in PluginDocsHandler less strict.
Merge pull request #1285 from crobinsonut/P44014493"""
__date__ = '2013-02-19 05:08:08 -0800'
__commit__ = '7b835a3c3ff57d5dc2d007b6458b23693c2d251b'
