
# This file is automatically generated

__version__ = '0.1.7'
__revision__ = """revno: 566 [merge]
tags: T478
committer: Tina G Grzincic <tina.g.grzincic@nasa.gov>
branch nick: TG-T478-MoveImages
timestamp: Mon 2011-05-30 13:48:16 -0400
message:
  T478 - Moved all images from the main docs directory into the appropriate 
  directory with the .rst file containing the directive that points to each 
  image.
"""
__date__ = '2011-06-01'
