
# This file is automatically generated

__version__ = '0.9.5'
__comments__ = """Detect and log when _repair_traits is not properly set up.
Merge pull request #1586 from setowns1/bug"""
__date__ = '2014-01-22 11:02:10 -0800'
__commit__ = '98907bff10942f02b6368fc851e67f26a9a3628d'
