
# This file is automatically generated

__version__ = '0.0.5'
__revision__ = """revno: 341
committer: Bret Naylor <bret@ubuntu>
branch nick: openmdao
timestamp: Thu 2010-04-15 14:30:37 -0400
message:
  mkrelease.py fix
"""
__date__ = '2010-04-15'
