
# This file is automatically generated

__version__ = '0.0.15'
__revision__ = """revno: 400
committer: banaylor <banaylor@GR200807772>
branch nick: windows_fixes
timestamp: Wed 2010-04-21 16:36:44 -0400
message:
  fabfile update
"""
__date__ = '2010-04-21'
