
# This file is automatically generated

__version__ = '0.0.14'
__revision__ = """revno: 396
committer: banaylor <banaylor@GR200807772>
branch nick: windows_fixes
timestamp: Wed 2010-04-21 16:19:49 -0400
message:
  "updating release info files"
"""
__date__ = '2010-04-21'
