
# This file is automatically generated

__version__ = '0.1.3'
__revision__ = """revno: 531
committer: tgrzinci <tgrzinci@storm>
branch nick: Test-Rel013
timestamp: Tue 2011-02-08 16:33:16 -0500
message:
  Updating release scripts and processes for the OpenMDAO Release 0.1.3 
"""
__date__ = '2011-02-08'
