
# This file is automatically generated

__version__ = '0.9.1'
__comments__ = """fix in expression gradients for Herb
Merge pull request #1504 from Kenneth-T-Moore/herb"""
__date__ = '2013-12-03 11:48:02 -0800'
__commit__ = '022052ae1a1e04d29f6e127feb46170d07ce517c'
