
# This file is automatically generated

__version__ = '0.2.1'
__comments__ = """updating license to Apache
Merge pull request #625 from naylor-b/update_license"""
__date__ = '2011-10-11 07:43:03 -0700'
__commit__ = '1be4ae5f191c245f3a4f509a406af98c71822e64'
