CGAMA
C
C     CALCULATE SPECIFIC HEAT RATIO FOR MIXTURE
      SUBROUTINE GAMA(P,T,F,W,GAMX)
      CALL CPA(P,T,F,W,CPAX)
      IF(F)2,2,1
1     CALL CPF(P,T,F,W,CPFX)
2     IF(W)4,4,3
3     CALL CPW(P,T,F,W,CPWX)
4     CPGX=(CPAX+F*CPFX+W*CPWX)/(1.+F+W)
      CALL R(P,T,F,W,RX)
      GAMX=CPGX/(CPGX-RX/778.161)
      RETURN
      END
