"""
Translation from NPSS units to OpenMDAO units.
NPSS unit strings taken from /NPSS/dev/Executive/src/Common/UnitNames.ncp
"""

__all__ = ('UNITS_MAP',)
__version__ = '0.1'

from openmdao.main.variable import UNDEFINED

# UNDEFINED => not specified.
# None      => unitless.
UNITS_MAP = {
   '' : UNDEFINED,

   'atm' : UNDEFINED,

   'bar' : UNDEFINED, 
   'Btu' : UNDEFINED,
   'Btu/hr' : UNDEFINED,
   'Btu/(hr*ft*F)' : UNDEFINED,
   'Btu/(hr*ft2)' : UNDEFINED,
   'Btu/(hr*ft2*F)' : UNDEFINED,
   'Btu/(hr*ft3)' : UNDEFINED,
   'Btu/lbm' : UNDEFINED,
   'Btu/(lbm*R)' : UNDEFINED,
   'Btu/(lbm*R*R)' : UNDEFINED,
   'Btu/(lbm*R)' : UNDEFINED,
   'Btu/(lbm*sec)' : UNDEFINED,
   'Btu/R' : UNDEFINED,
   'Btu/(R*in)' : UNDEFINED,
   'Btu/sec' : UNDEFINED,
   'Btu/(sec*ft*R)' : UNDEFINED,
   'Btu/(sec*ft2)' : UNDEFINED,
   'Btu/(sec*in*R)' : UNDEFINED,
   'Btu/(sec*in2*R)' : UNDEFINED, 
   'Btu/(sec*R)' : UNDEFINED,
   'Btu*sec2/(lbm*ft2)' : UNDEFINED,

   'C' : UNDEFINED,
   'cm' : 'cm',
   'cm2' : 'cm**2',
   'cm3' : 'cm**3',
   'cm4' : 'cm**4',
   'cm5' : 'cm**5',

   'daN' : UNDEFINED,
   'day' : UNDEFINED,
   'dC' : UNDEFINED,
   'deg' : 'deg',
   'dF' : UNDEFINED,
   'dK' : UNDEFINED,
   'dR' : UNDEFINED,

   'F' : UNDEFINED,
   'ft' : 'ft',
   'ft*lbf' : UNDEFINED,
   'ft*lbf*in3/(lbm*rad*rad)' : UNDEFINED,
   'ft*lbf/Btu' : UNDEFINED,
   'ft*lbf/(R*lbm)' : UNDEFINED,
   'ft*lbf/(R*lbmol)' : UNDEFINED,
   'ft*lbf/rad' : UNDEFINED,
   'ft*lbf/(rad*sec)' : UNDEFINED,
   'ft*lbf/sec' : UNDEFINED,
   'ft*lbm/(lbf*sec2)' : UNDEFINED,
   'ft/sec' : 'ft/s',
   'ft/sec2' : 'ft/s**2',
   'ft2' : 'ft**2',
   'ft2*lbm' : UNDEFINED,
   'ft2/sec2' : 'ft**2/s**2',
   'ft2/(sec2*R)' : UNDEFINED,
   'ft3' : 'ft**3',
   'ft3/lbm' : UNDEFINED,

   'gal' : UNDEFINED,
   'gal*in/(min*SQRT_lbf)' : UNDEFINED,
   'grains' : UNDEFINED,
   'g/sec' : UNDEFINED,

   'hbar' : UNDEFINED,
   'Hz' : 'Hz',
   'hp' : UNDEFINED,
   'hp/ft2' : UNDEFINED,
   'hr' : UNDEFINED,
   'hp*hr' : UNDEFINED,

   'in' : 'inch',
   'in*lbf*sec2/lbm' : UNDEFINED,
   'in/sec' : 'inch/s',
   'in2' : 'inch**2',
   'in2/lbf' : UNDEFINED,
   'in3' : 'inch**3',
   'in3*sec/rad' : UNDEFINED,
   'in4' : 'inch**4',
   'in4*sec2/(lbm*ft)' : UNDEFINED,
   'in5' : 'inch**5',
   'inH2O' : UNDEFINED,
   'inHg' : UNDEFINED,

   'J/kg' : UNDEFINED,
   'J/(kg*K)' : UNDEFINED,
   'J/sec' : UNDEFINED,
   'J' : UNDEFINED,

   'K' : UNDEFINED,
   'kg' : 'kg',
   'kg*m2' : 'kg*m**2',
   'kg/J' : UNDEFINED,
   'kg/m3' : 'kg/m**3',
   'kg/(N*sec)' : 'kg/(N*s)',
   'kg/sec' : 'kg/s',
   'kJ/kg' : UNDEFINED,
   'kJ/(kg*K)' : UNDEFINED,
   'km' : 'km',
   'kN' : 'kN',
   'knot' : UNDEFINED,
   'kPa' : UNDEFINED,
   'kW' : 'kW',

   'lbf' : UNDEFINED,
   'lbf*in*sec2/lbm' : UNDEFINED,
   'lbf*in2' : UNDEFINED,
   'lbf*in4*sec2/lbm' : UNDEFINED,
   'lbf/ft2' : UNDEFINED,
   'lbf*sec/(lbm*in2)' : UNDEFINED,
   'lbf*sec2/(lbm*in5)' : UNDEFINED,
   'lbf*sec2/(lbm*in2)' : UNDEFINED,
   'lbm' : UNDEFINED,
   'lbm*in2' : UNDEFINED,
   'lbm/(ft*sec)' : UNDEFINED,
   'lbm/(ft*sec2)' : UNDEFINED,
   'lbm/ft3' : UNDEFINED,
   'lbm/(ft3*sec)' : UNDEFINED,
   'lbm/hr' : UNDEFINED,
   'lbm/(hr*hp)' : UNDEFINED,
   'lbm/(hr*lbf)' : UNDEFINED,
   'lbm/(in*sec)' : UNDEFINED,
   'lbm/in2' : UNDEFINED,
   'lbm/in3' : UNDEFINED,
   'lbm/(in3*sec)' : UNDEFINED,
   'lbm/lbm' : UNDEFINED,
   'lbm/mol' : UNDEFINED,
   'lbm/sec' : UNDEFINED,
   'lbm/(sec*ft2)' : UNDEFINED, 
   'lbm/(sec*in2)' : UNDEFINED, 
   'lbm/sec2' : UNDEFINED,
   'lbm*R/sec' : UNDEFINED,
   'lbm*SQRT_R/psia' : UNDEFINED,
   'lbm*lbm*in2/(lbf*sec2)' : UNDEFINED,
   'lbm*lbm/sec2' : UNDEFINED,
   'lbmol' : UNDEFINED,
   'liter' : 'l',

   'm' : 'm',
   'm/sec' : 'm/s',
   'm/sec2' : 'm/s**2',
   'm2' : 'm**2',
   'm3' : 'm**3',
   'mbar' : UNDEFINED,
   'MPa' : UNDEFINED, 
   'mg/J' : UNDEFINED,
   'mg/(N*sec)' : UNDEFINED,
   'mil' : UNDEFINED,
   'min' : 'min',
   'mm' : 'mm',
   'mm2' : 'mm**2',
   'mm3' : 'mm**3',
   'mm4' : 'mm**4',
   'mm5' : 'mm**5',
   'mol' : UNDEFINED,

   'N' : 'N',
   'N*m' : 'N*m',
   'N/m2' : 'N/m**2',
   'nmile' : UNDEFINED,
   'none' : None,
 
   'Pa' : UNDEFINED,
   '1/rpm' : UNDEFINED,
   '1/sec' : UNDEFINED,
   'psia' : UNDEFINED,
   'psia/sec' : UNDEFINED,
   'R/sec' : UNDEFINED,
   'rad' : UNDEFINED,
   'rad/sec' : UNDEFINED,
   'R' : UNDEFINED,
   'R/sec' : UNDEFINED,
   'rev' : UNDEFINED,
   'rev/sec' : UNDEFINED,
   'rpm' : '1/min',
   'rpm/sec' : UNDEFINED,
   'rpm/SQRT_R' : UNDEFINED,

   'sec' : 's',
   'sec2' : 's**2',
   'slug' : UNDEFINED,
   'slug*ft2' : UNDEFINED,
   'slug/ft3' : UNDEFINED,
   'SQRT_lbf' : UNDEFINED,
   'SQRT_N' : UNDEFINED,
   'SQRT_R' : UNDEFINED,

   'W' : UNDEFINED,
   'W/(m*K)' : UNDEFINED,
   'W/m2' : UNDEFINED,
   'W/(m2*K)' : UNDEFINED,
   'W/m3' : UNDEFINED,

   'yd' : UNDEFINED,
}

