
# This file is automatically generated

__version__ = '0.9.0'
__comments__ = """Merge branch 'dev' of http://github.com/OpenMDAO/OpenMDAO-Framework into dev"""
__date__ = '2013-11-12 18:28:41 -0500'
__commit__ = 'af7ca6336c09cff02d699006655399d322d92aa0'
