
# This file is automatically generated

__version__ = '0.8.0'
__comments__ = """testhosts.cfg edit before release
Merge pull request #1410 from kmarsteller/dev"""
__date__ = '2013-07-19 17:35:53 -0700'
__commit__ = '1f9a61fa9d68458e5d5feeeb04f345d1321562ae'
