      SUBROUTINE AVOL(X,D,N,VOLUME,VLNOSE,VLTAIL)
                   
C   ROUTINE TO COMPUTE THE SURFACE AREA AND VOLUME OF A BODY OF
C     REVOULTION DEFINED BY A TABLE OF POINTS.
C   INPUT VARIABLES:
C     X        ARRAY OF FUS. STATIONS AT WHICH BODY IS DEFINED
C     D        CORRESPONDING ARRAY OF DIAMETERS.
C     N        LENGTH OF ARRAYS X AND D.
C   OUTPUT VARIABLES:
C     AREA     SURFACE AREA
C     VOLUME   VOLUME OF BODY
                   
      DIMENSION X(N),D(N)
      DATA PI/3.141593/
                   
      SUM1=0.      
      SUM2=0.      
      DO 10 I=2,N
      DX=X(I)-X(I-1)
      DR=0.5*(D(I)-D(I-1))
      SUM1=SUM1+(D(I)+D(I-1))*SQRT(DR*DR+DX*DX)
      SUM2=SUM2+DX*(D(I)*D(I)+D(I-1)*D(I-1))

C---- FIND SUM2 FOR FOREBODY AND AFTERBODY FOR PDCYL
      IF (I .EQ. 21) SUMNOSE = SUM2
      IF (I .EQ. (N-20)) SUMTAIL = SUM2


10    CONTINUE
      AREA  = .5*PI*SUM1
      VOLUME = .125*PI*SUM2

C---- CALCULATE FOREBODY VOLUME AND AFTERBODY VOLUME FOR PDCYL
      VLNOSE = 0.125 * PI * SUMNOSE
      VLUPTL = 0.125 * PI * SUMTAIL
      VLTAIL = VOLUME - VLUPTL

      RETURN
      END
