
# This file is automatically generated

__version__ = '0.1.2'
__revision__ = """revno: 364
committer: Bret Naylor <bnaylor@grc.nasa.gov>
branch nick: packaging
timestamp: Wed 2010-04-07 08:39:06 -0400
message:
  fixes to mkinstaller and created a fabric script to automatically build openmdao source distribs and place them on the server
"""
__date__ = '2010-04-07'
