
# This file is automatically generated

__version__ = '0.0.14'
__revision__ = """revno: 439
committer: banaylor <banaylor@GR200807772>
branch nick: windows_fixes
timestamp: Fri 2010-04-23 17:15:13 -0400
message:
  "updating release info and sphinx config files"
"""
__date__ = '2010-04-23'
