
# This file is automatically generated

__version__ = '0.1.1'
__revision__ = """revno: 363
committer: Bret Naylor <bnaylor@grc.nasa.gov>
branch nick: packaging
timestamp: Tue 2010-04-06 16:10:02 -0400
message:
  working on deployment using virtualenv
"""
__date__ = '2010-04-07'
