
# This file is automatically generated

__version__ = '0.0.11'
__revision__ = """revno: 425
committer: Bret Naylor <Bret.A.Naylor@nasa.gov>
branch nick: windows_fixes
timestamp: Thu 2010-04-22 18:56:47 -0400
message:
  updated mkrelease.py
"""
__date__ = '2010-04-22'
