
# This file is automatically generated

__version__ = '0.0.1'
__revision__ = """revno: 362
committer: Bret Naylor <Bret.A.Naylor@nasa.gov>
branch nick: packaging
timestamp: Mon 2010-04-05 19:06:33 -0400
message:
  interim commit
"""
__date__ = '2010-04-06'
