
# This file is automatically generated

__version__ = '0.1.0'
__revision__ = """revno: 474
committer: banaylor <banaylor@storm>
branch nick: trunk
timestamp: Thu 2010-09-09 15:14:48 -0400
message:
  added singleEI example to mkinstaller.py
"""
__date__ = '2010-09-09'
