
# This file is automatically generated

__version__ = '0.5.6'
__comments__ = """Merge branch 'remote_py_cmd' of github.com:kmarsteller/OpenMDAO-Framework into remote_py_cmd"""
__date__ = '2013-04-12 16:15:30 -0400'
__commit__ = 'fc2518017b0ad224e3488c47ad47dbcb6a48564d'
