
# This file is automatically generated

__version__ = '0.1'
__revision__ = """revno: 378
committer: Bret Naylor <bnaylor@grc.nasa.gov>
branch nick: packaging
timestamp: Mon 2010-04-12 10:52:35 -0400
message:
  build_docs now updates the version info in the sphinx conf.py file
"""
__date__ = '2010-04-12'
