
# This file is automatically generated

__version__ = '0.0.10'
__revision__ = """revno: 362
committer: Bret Naylor <bnaylor@grc.nasa.gov>
branch nick: windows_fixes
timestamp: Tue 2010-04-20 11:50:20 -0400
message:
  changed from distribute to setuptools in the go-openmdao.py installer because distribute requires elevation on Vista
"""
__date__ = '2010-04-20'
